version: '3.5'
services:
  cadvisor:
    image: 'google/cadvisor:latest'
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
      - '/dev/kmsg:/dev/kmsg:ro'
  grafana:
    image: grafana/grafana
    ports:
      - '3004:3000'
    restart: on-failure
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_AUTH_ANONYMOUS_ENABLED: 'True'
      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor # use Viewer for production
    restart: on-failure
    volumes:
      - './grafana/grafanaDatasources.yml:/etc/grafana/provisioning/datasources/datasources.yml'
      - './grafana/grafanaDashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml'
      - './grafana/dashboards:/var/lib/grafana/dashboards'
  node-exporter:
    image: 'prom/node-exporter:latest'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - >-
        --collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"
      - >-
        --collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse.lxc|mqueue)(fs|)$$"
    restart: unless-stopped
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
  prometheus:
    image: 'prom/prometheus:latest'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    depends_on:
      - cadvisor
      - node-exporter
    ports:
      - '9090:9090'
    restart: on-failure
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
